package yang.app.qt.black;

import io.qt.QUiForm;
import io.qt.core.QCoreApplication;
import io.qt.core.QRect;
import io.qt.core.QSize;
import io.qt.core.Qt;
import io.qt.core.Qt.AlignmentFlag;
import io.qt.core.Qt.CursorShape;
import io.qt.core.Qt.LayoutDirection;
import io.qt.core.Qt.Orientation;
import io.qt.widgets.QCheckBox;
import io.qt.widgets.QComboBox;
import io.qt.gui.QCursor;
import io.qt.widgets.QDialog;
import io.qt.widgets.QFontComboBox;
import io.qt.widgets.QGroupBox;
import io.qt.widgets.QLabel;
import io.qt.widgets.QLineEdit;
import io.qt.widgets.QLineEdit.EchoMode;
import io.qt.widgets.QPushButton;
import io.qt.widgets.QRadioButton;
import io.qt.widgets.QSlider;
import io.qt.widgets.QSlider.TickPosition;
import io.qt.widgets.QSpinBox;
import io.qt.widgets.QTabWidget;
import io.qt.widgets.QTabWidget.TabPosition;
import io.qt.widgets.QTabWidget.TabShape;
import io.qt.widgets.QWidget;

public class Ui_settings
  implements QUiForm<QDialog>
{
  public QTabWidget taps;
  public QWidget first_tap;
  public QGroupBox groupBox_9;
  public QCheckBox topKeywords;
  public QSpinBox topKeywordsCount;
  public QCheckBox onlyAPart;
  public QWidget editorsettings_tap;
  public QGroupBox groupBox;
  public QFontComboBox fontComboBox;
  public QLabel label;
  public QLabel label_7;
  public QSpinBox fontsize;
  public QGroupBox groupBox_2;
  public QLabel label_3;
  public QLabel label_4;
  public QLabel label_5;
  public QSpinBox firstline;
  public QSpinBox paragraphspace;
  public QSpinBox linespace;
  public QGroupBox groupBox_3;
  public QLabel label_6;
  public QSpinBox textCursorWidth;
  public QComboBox zoom;
  public QLabel label_2;
  public QSpinBox documentmargin;
  public QLabel label_8;
  public QWidget writingview_tap;
  public QGroupBox groupBox_4;
  public QSlider textWidth;
  public QGroupBox groupBox_5;
  public QSlider alpha;
  public QGroupBox groupBox_6;
  public QRadioButton fullscreen;
  public QRadioButton window;
  public QGroupBox groupBox_10;
  public QSlider shadowSize;
  public QWidget savesettings_tap;
  public QGroupBox groupBox_7;
  public QCheckBox savecheckBox;
  public QLabel savelable;
  public QSpinBox savetime;
  public QGroupBox groupBox_8;
  public QCheckBox savegitinfo;
  public QPushButton gitstartwork;
  public QLabel label_11;
  public QLineEdit gitpassword;
  public QLabel label_10;
  public QLineEdit gitusername;
  public QLabel label_9;
  public QLineEdit githost;
  
  public void setupUi(QDialog settings)
  {
    settings.setObjectName("settings");
    settings.resize(new QSize(510, 375).expandedTo(settings.minimumSizeHint()));
    this.taps = new QTabWidget(settings);
    this.taps.setObjectName("taps");
    this.taps.setEnabled(true);
    this.taps.setGeometry(new QRect(4, 10, 502, 361));
    this.taps.setCursor(new QCursor(Qt.CursorShape.ArrowCursor));
    this.taps.setTabPosition(QTabWidget.TabPosition.North);
    this.taps.setTabShape(QTabWidget.TabShape.Rounded);
    this.taps.setDocumentMode(false);
    this.first_tap = new QWidget();
    this.first_tap.setObjectName("first_tap");
    this.groupBox_9 = new QGroupBox(this.first_tap);
    this.groupBox_9.setObjectName("groupBox_9");
    this.groupBox_9.setGeometry(new QRect(10, 10, 481, 111));
    this.topKeywords = new QCheckBox(this.groupBox_9);
    this.topKeywords.setObjectName("topKeywords");
    this.topKeywords.setGeometry(new QRect(20, 26, 231, 18));
    this.topKeywordsCount = new QSpinBox(this.groupBox_9);
    this.topKeywordsCount.setObjectName("topKeywordsCount");
    this.topKeywordsCount.setGeometry(new QRect(50, 50, 41, 21));
    this.topKeywordsCount.setFrame(true);
    this.onlyAPart = new QCheckBox(this.groupBox_9);
    this.onlyAPart.setObjectName("onlyAPart");
    this.onlyAPart.setGeometry(new QRect(20, 80, 351, 18));
    this.taps.addTab(this.first_tap, QCoreApplication.translate("settings", "关键词列表", null));
    this.editorsettings_tap = new QWidget();
    this.editorsettings_tap.setObjectName("editorsettings_tap");
    this.groupBox = new QGroupBox(this.editorsettings_tap);
    this.groupBox.setObjectName("groupBox");
    this.groupBox.setGeometry(new QRect(10, 10, 481, 61));
    this.fontComboBox = new QFontComboBox(this.groupBox);
    this.fontComboBox.setObjectName("fontComboBox");
    this.fontComboBox.setGeometry(new QRect(86, 21, 231, 22));
    this.label = new QLabel(this.groupBox);
    this.label.setObjectName("label");
    this.label.setGeometry(new QRect(10, 21, 71, 22));
    this.label.setAlignment( Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.label_7 = new QLabel(this.groupBox);
    this.label_7.setObjectName("label_7");
    this.label_7.setGeometry(new QRect(350, 21, 51, 22));
    this.label_7.setLayoutDirection(Qt.LayoutDirection.LeftToRight);
    this.label_7.setAlignment(Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.fontsize = new QSpinBox(this.groupBox);
    this.fontsize.setObjectName("fontsize");
    this.fontsize.setGeometry(new QRect(405, 21, 51, 22));
    this.groupBox_2 = new QGroupBox(this.editorsettings_tap);
    this.groupBox_2.setObjectName("groupBox_2");
    this.groupBox_2.setGeometry(new QRect(10, 75, 481, 61));
    this.label_3 = new QLabel(this.groupBox_2);
    this.label_3.setObjectName("label_3");
    this.label_3.setGeometry(new QRect(10, 23, 51, 22));
    this.label_3.setAlignment(Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.label_4 = new QLabel(this.groupBox_2);
    this.label_4.setObjectName("label_4");
    this.label_4.setGeometry(new QRect(160, 23, 71, 22));
    this.label_4.setAlignment(Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.label_5 = new QLabel(this.groupBox_2);
    this.label_5.setObjectName("label_5");
    this.label_5.setGeometry(new QRect(325, 23, 71, 22));
    this.label_5.setAlignment(Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.firstline = new QSpinBox(this.groupBox_2);
    this.firstline.setObjectName("firstline");
    this.firstline.setGeometry(new QRect(396, 23, 61, 22));
    this.paragraphspace = new QSpinBox(this.groupBox_2);
    this.paragraphspace.setObjectName("paragraphspace");
    this.paragraphspace.setGeometry(new QRect(230, 23, 61, 22));
    this.linespace = new QSpinBox(this.groupBox_2);
    this.linespace.setObjectName("linespace");
    this.linespace.setGeometry(new QRect(64, 23, 61, 22));
    this.groupBox_3 = new QGroupBox(this.editorsettings_tap);
    this.groupBox_3.setObjectName("groupBox_3");
    this.groupBox_3.setGeometry(new QRect(10, 141, 481, 61));
    this.label_6 = new QLabel(this.groupBox_3);
    this.label_6.setObjectName("label_6");
    this.label_6.setGeometry(new QRect(10, 23, 81, 22));
    this.label_6.setAlignment(Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.textCursorWidth = new QSpinBox(this.groupBox_3);
    this.textCursorWidth.setObjectName("textCursorWidth");
    this.textCursorWidth.setGeometry(new QRect(91, 23, 41, 22));
    this.textCursorWidth.setMinimum(1);
    this.zoom = new QComboBox(this.groupBox_3);
    this.zoom.setObjectName("zoom");
    this.zoom.setGeometry(new QRect(220, 23, 71, 22));
    this.label_2 = new QLabel(this.groupBox_3);
    this.label_2.setObjectName("label_2");
    this.label_2.setGeometry(new QRect(160, 23, 61, 22));
    this.label_2.setAlignment(Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.documentmargin = new QSpinBox(this.groupBox_3);
    this.documentmargin.setObjectName("documentmargin");
    this.documentmargin.setGeometry(new QRect(385, 23, 41, 22));
    this.documentmargin.setMinimum(1);
    this.label_8 = new QLabel(this.groupBox_3);
    this.label_8.setObjectName("label_8");
    this.label_8.setGeometry(new QRect(313, 23, 71, 22));
    this.label_8.setAlignment(Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.taps.addTab(this.editorsettings_tap, QCoreApplication.translate("settings", "编辑器", null));
    this.writingview_tap = new QWidget();
    this.writingview_tap.setObjectName("writingview_tap");
    this.groupBox_4 = new QGroupBox(this.writingview_tap);
    this.groupBox_4.setObjectName("groupBox_4");
    this.groupBox_4.setGeometry(new QRect(10, 10, 301, 46));
    this.textWidth = new QSlider(this.groupBox_4);
    this.textWidth.setObjectName("textWidth");
    this.textWidth.setGeometry(new QRect(10, 20, 281, 16));
    this.textWidth.setTracking(true);
    this.textWidth.setOrientation(Qt.Orientation.Horizontal);
    this.textWidth.setTickPosition(QSlider.TickPosition.NoTicks);
    this.groupBox_5 = new QGroupBox(this.writingview_tap);
    this.groupBox_5.setObjectName("groupBox_5");
    this.groupBox_5.setGeometry(new QRect(270, 62, 221, 46));
    this.alpha = new QSlider(this.groupBox_5);
    this.alpha.setObjectName("alpha");
    this.alpha.setGeometry(new QRect(10, 20, 201, 16));
    this.alpha.setMinimum(0);
    this.alpha.setMaximum(255);
    this.alpha.setSliderPosition(1);
    this.alpha.setTracking(true);
    this.alpha.setOrientation(Qt.Orientation.Horizontal);
    this.alpha.setInvertedControls(false);
    this.alpha.setTickPosition(QSlider.TickPosition.NoTicks);
    this.groupBox_6 = new QGroupBox(this.writingview_tap);
    this.groupBox_6.setObjectName("groupBox_6");
    this.groupBox_6.setGeometry(new QRect(320, 10, 171, 46));
    this.fullscreen = new QRadioButton(this.groupBox_6);
    this.fullscreen.setObjectName("fullscreen");
    this.fullscreen.setGeometry(new QRect(10, 18, 61, 19));
    this.window = new QRadioButton(this.groupBox_6);
    this.window.setObjectName("window");
    this.window.setGeometry(new QRect(90, 18, 61, 19));
    this.groupBox_10 = new QGroupBox(this.writingview_tap);
    this.groupBox_10.setObjectName("groupBox_10");
    this.groupBox_10.setGeometry(new QRect(10, 62, 251, 46));
    this.shadowSize = new QSlider(this.groupBox_10);
    this.shadowSize.setObjectName("shadowSize");
    this.shadowSize.setGeometry(new QRect(10, 20, 231, 16));
    this.shadowSize.setMinimum(0);
    this.shadowSize.setMaximum(400);
    this.shadowSize.setSliderPosition(1);
    this.shadowSize.setTracking(true);
    this.shadowSize.setOrientation(Qt.Orientation.Horizontal);
    this.shadowSize.setInvertedControls(false);
    this.shadowSize.setTickPosition(QSlider.TickPosition.NoTicks);
    this.taps.addTab(this.writingview_tap, QCoreApplication.translate("settings", "写作视图", null));
    this.savesettings_tap = new QWidget();
    this.savesettings_tap.setObjectName("savesettings_tap");
    this.groupBox_7 = new QGroupBox(this.savesettings_tap);
    this.groupBox_7.setObjectName("groupBox_7");
    this.groupBox_7.setGeometry(new QRect(10, 9, 481, 61));
    this.savecheckBox = new QCheckBox(this.groupBox_7);
    this.savecheckBox.setObjectName("savecheckBox");
    this.savecheckBox.setGeometry(new QRect(20, 25, 101, 19));
    this.savelable = new QLabel(this.groupBox_7);
    this.savelable.setObjectName("savelable");
    this.savelable.setGeometry(new QRect(130, 25, 241, 16));
    this.savelable.setAlignment(Qt.AlignmentFlag.AlignRight, Qt.AlignmentFlag.AlignVCenter);
    this.savetime = new QSpinBox(this.groupBox_7);
    this.savetime.setObjectName("savetime");
    this.savetime.setGeometry(new QRect(372, 23, 49, 21));
    this.savetime.setMinimum(1);
    this.savetime.setMaximum(3600);
    this.groupBox_8 = new QGroupBox(this.savesettings_tap);
    this.groupBox_8.setObjectName("groupBox_8");
    this.groupBox_8.setGeometry(new QRect(10, 75, 481, 161));
    this.savegitinfo = new QCheckBox(this.groupBox_8);
    this.savegitinfo.setObjectName("savegitinfo");
    this.savegitinfo.setGeometry(new QRect(20, 130, 101, 19));
    this.gitstartwork = new QPushButton(this.groupBox_8);
    this.gitstartwork.setObjectName("gitstartwork");
    this.gitstartwork.setGeometry(new QRect(340, 130, 131, 24));
    this.label_11 = new QLabel(this.groupBox_8);
    this.label_11.setObjectName("label_11");
    this.label_11.setGeometry(new QRect(20, 100, 84, 20));
    this.gitpassword = new QLineEdit(this.groupBox_8);
    this.gitpassword.setObjectName("gitpassword");
    this.gitpassword.setGeometry(new QRect(110, 100, 361, 20));
    this.gitpassword.setEchoMode(QLineEdit.EchoMode.Password);
    this.label_10 = new QLabel(this.groupBox_8);
    this.label_10.setObjectName("label_10");
    this.label_10.setGeometry(new QRect(20, 70, 84, 20));
    this.gitusername = new QLineEdit(this.groupBox_8);
    this.gitusername.setObjectName("gitusername");
    this.gitusername.setGeometry(new QRect(110, 70, 361, 20));
    this.label_9 = new QLabel(this.groupBox_8);
    this.label_9.setObjectName("label_9");
    this.label_9.setGeometry(new QRect(20, 30, 111, 20));
    this.githost = new QLineEdit(this.groupBox_8);
    this.githost.setObjectName("githost");
    this.githost.setGeometry(new QRect(140, 30, 331, 20));
    this.taps.addTab(this.savesettings_tap, QCoreApplication.translate("settings", "保存选项", null));
    retranslateUi(settings);
    
    this.taps.setCurrentIndex(2);
    
//    settings.connectSlotsByName();
  }
  
  void retranslateUi(QDialog settings)
  {
    settings.setWindowTitle(QCoreApplication.translate("settings", "Dialog", null));
    this.groupBox_9.setTitle(QCoreApplication.translate("settings", "关键词预测", null));
    this.topKeywords.setToolTip(QCoreApplication.translate("settings", "勾选此项能够显著提升关键词列表框的显示速度（在编辑长文档且定义了大量关键词时效果明显）", null));
    this.topKeywords.setText(QCoreApplication.translate("settings", "置顶的关键词达到此数量时停止预测：", null));
    this.onlyAPart.setToolTip(QCoreApplication.translate("settings", "勾选此项可加快文档内容分析及预测速度", null));
    this.onlyAPart.setText(QCoreApplication.translate("settings", "预测时仅分析文档中的部分文本，而非整个文档", null));
    this.taps.setTabText(this.taps.indexOf(this.first_tap), QCoreApplication.translate("settings", "关键词列表", null));
    this.groupBox.setTitle(QCoreApplication.translate("settings", "字体与字号", null));
    this.label.setText(QCoreApplication.translate("settings", "默认字体：", null));
    this.label_7.setText(QCoreApplication.translate("settings", "字号：", null));
    this.groupBox_2.setTitle(QCoreApplication.translate("settings", "段落", null));
    this.label_3.setText(QCoreApplication.translate("settings", "行距：", null));
    this.label_4.setText(QCoreApplication.translate("settings", "段落间距：", null));
    this.label_5.setText(QCoreApplication.translate("settings", "首行缩进：", null));
    this.groupBox_3.setTitle(QCoreApplication.translate("settings", "其他", null));
    this.label_6.setText(QCoreApplication.translate("settings", "插入符宽度：", null));
    this.label_2.setText(QCoreApplication.translate("settings", "缩放值：", null));
    this.label_8.setText(QCoreApplication.translate("settings", "页边距：", null));
    this.taps.setTabText(this.taps.indexOf(this.editorsettings_tap), QCoreApplication.translate("settings", "编辑器", null));
    this.groupBox_4.setTitle(QCoreApplication.translate("settings", "编辑器宽度", null));
    this.groupBox_5.setTitle(QCoreApplication.translate("settings", "页面阴影浓度", null));
    this.groupBox_6.setTitle(QCoreApplication.translate("settings", "视图模式", null));
    this.fullscreen.setText(QCoreApplication.translate("settings", "全屏", null));
    this.window.setText(QCoreApplication.translate("settings", "窗口", null));
    this.groupBox_10.setTitle(QCoreApplication.translate("settings", "页面阴影大小", null));
    this.taps.setTabText(this.taps.indexOf(this.writingview_tap), QCoreApplication.translate("settings", "写作视图", null));
    this.groupBox_7.setTitle(QCoreApplication.translate("settings", "自动保存", null));
    this.savecheckBox.setText(QCoreApplication.translate("settings", "启用自动保存", null));
    this.savelable.setText(QCoreApplication.translate("settings", "文档更改超过此时间后自动保存(秒)：", null));
    this.groupBox_8.setTitle(QCoreApplication.translate("settings", "备份项目到Git远程仓库", null));
    this.savegitinfo.setText(QCoreApplication.translate("settings", "记住凭据", null));
    this.gitstartwork.setText(QCoreApplication.translate("settings", "连接仓库并上传项目", null));
    this.label_11.setText(QCoreApplication.translate("settings", "密码：", null));
    this.label_10.setText(QCoreApplication.translate("settings", "用户名：", null));
    this.label_9.setText(QCoreApplication.translate("settings", "仓库地址(https)：", null));
    this.taps.setTabText(this.taps.indexOf(this.savesettings_tap), QCoreApplication.translate("settings", "保存选项", null));
  }
}
