package yang.app.qt.black;

import io.qt.QUiForm;
import io.qt.core.QCoreApplication;
import io.qt.core.QEvent;
import io.qt.core.QObject;
import io.qt.core.QRect;
import io.qt.core.QSize;
import io.qt.core.Qt;
import io.qt.core.Qt.DockWidgetArea;
import io.qt.widgets.QAction;
import io.qt.widgets.QDockWidget;
import io.qt.widgets.QDockWidget.DockWidgetFeature;
import io.qt.gui.QIcon;
import io.qt.widgets.QMainWindow;
import io.qt.widgets.QMenu;
import io.qt.widgets.QMenuBar;
import io.qt.gui.QPixmap;
import io.qt.widgets.QSizePolicy;
import io.qt.widgets.QSizePolicy.Policy;
import io.qt.widgets.QVBoxLayout;
import io.qt.widgets.QWidget;

public class Ui_black
  implements QUiForm<QMainWindow>
{
  public QAction addFile;
  public QAction addDir;
  public QAction addKeywords;
  public QAction newProject;
  public QAction openProject;
  public QAction find;
  public QAction moveToRecycle;
  public QAction clearRecycle;
  public QAction setGit;
  public QAction commit;
  public QAction push;
  public QAction commitAndPush;
  public QAction branchTool;
  public QAction charCount;
  public QAction oneChineseName;
  public QAction chineseNames;
  public QAction engManName;
  public QAction engWomanName;
  public QAction itManName;
  public QAction itWomanName;
  public QAction writingview;
  public QAction settings;
  public QAction resetProject;
  public QAction about,howPay;
  public QAction saveProjectAllChanged;
  public QAction openProjectDir;
  public QAction clearTempFiles;
  public QAction clearLogs;
  public QAction hideFilePanel;
  public QAction checkUpdate;
  public QWidget centralwidget;
  public QVBoxLayout verticalLayout;
  public QMenuBar menubar;
  public QMenu fileMenu;
  public QMenu editMenu;
  public QMenu projectMenu;
  public QMenu menu_4;
  public QMenu menu_5;
  public QMenu gitMenu;
  public QMenu toolsMenu;
  public QMenu getNames;
  public QMenu viewMenu;
  public QMenu helpMenu;
  public QDockWidget dockTree;
  public QWidget dockWidgetContents;
  QAction info;
  
  public void setupUi(QMainWindow black)
  {
    black.setObjectName("black");
    black.setEnabled(true);
//    black.resize(new QSize(856, 566).expandedTo(black.minimumSizeHint()));
//    QSizePolicy sizePolicy = new QSizePolicy(QSizePolicy.Policy.Ignored, QSizePolicy.Policy.Ignored);
//    sizePolicy.setHorizontalStretch((byte)0);
//    sizePolicy.setVerticalStretch((byte)0);
//    sizePolicy.setHeightForWidth(black.sizePolicy().hasHeightForWidth());
//    black.setSizePolicy(sizePolicy);
    black.setAutoFillBackground(false);
    black.setStyleSheet("");
    black.setProperty("setAutoFillBackground", Boolean.valueOf(false));
    this.addFile = new QAction(black);
    this.addFile.setObjectName("addFile");
    this.addFile.setIcon(new QIcon(new QPixmap("classpath:yang/app/qt/black/iconsScr/16/addfile.png")));
    this.addDir = new QAction(black);
    this.addDir.setObjectName("addDir");
    this.addDir.setIcon(new QIcon(new QPixmap("classpath:yang/app/qt/black/iconsScr/32/adddir.png")));
    this.addKeywords = new QAction(black);
    this.addKeywords.setObjectName("addKeywords");
    this.addKeywords.setIcon(new QIcon(new QPixmap("classpath:yang/app/qt/black/icons/push_pin_icon&48.png")));
    this.newProject = new QAction(black);
    this.newProject.setObjectName("newProject");
    this.openProject = new QAction(black);
    this.openProject.setObjectName("openProject");
    this.find = new QAction(black);
    this.find.setObjectName("find");
    this.moveToRecycle = new QAction(black);
    this.moveToRecycle.setObjectName("moveToRecycle");
    this.clearRecycle = new QAction(black);
    this.clearRecycle.setObjectName("clearRecycle");
    this.setGit = new QAction(black);
    this.setGit.setObjectName("setGit");
    this.commit = new QAction(black);
    this.commit.setObjectName("commit");
    this.push = new QAction(black);
    this.push.setObjectName("push");
    this.commitAndPush = new QAction(black);
    this.commitAndPush.setObjectName("commitAndPush");
    this.branchTool = new QAction(black);
    this.branchTool.setObjectName("branchTool");
    this.branchTool.setEnabled(false);
    this.charCount = new QAction(black);
    this.charCount.setObjectName("charCount");
    this.oneChineseName = new QAction(black);
    this.oneChineseName.setObjectName("oneChineseName");
    this.chineseNames = new QAction(black);
    this.chineseNames.setObjectName("chineseNames");
    this.engManName = new QAction(black);
    this.engManName.setObjectName("engManName");
    this.engWomanName = new QAction(black);
    this.engWomanName.setObjectName("engWomanName");
    this.itManName = new QAction(black);
    this.itManName.setObjectName("itManName");
    this.itWomanName = new QAction(black);
    this.itWomanName.setObjectName("itWomanName");
    this.writingview = new QAction(black);
    this.writingview.setObjectName("writingview");
    this.writingview.setIcon(new QIcon(new QPixmap("classpath:yang/app/qt/black/iconsScr/32/enterwritingview.png")));
    this.settings = new QAction(black);
    this.settings.setObjectName("settings");
    this.settings.setIcon(new QIcon(new QPixmap("classpath:yang/app/qt/black/icons/wrench_plus_2_icon&48.png")));
    this.resetProject = new QAction(black);
    this.resetProject.setObjectName("resetProject");
    this.about = new QAction(black);
    this.about.setObjectName("about");
    this.howPay = new QAction(black);
    this.howPay.setObjectName("howPay");
    this.info = new QAction(black);
    this.info.setObjectName("info");
    this.saveProjectAllChanged = new QAction(black);
    this.saveProjectAllChanged.setObjectName("saveProjectAllChanged");
    this.openProjectDir = new QAction(black);
    this.openProjectDir.setObjectName("openProjectDir");
    this.clearTempFiles = new QAction(black);
    this.clearTempFiles.setObjectName("clearTempFiles");
    this.clearLogs = new QAction(black);
    this.clearLogs.setObjectName("clearLogs");
    this.hideFilePanel = new QAction(black);
    this.hideFilePanel.setObjectName("hideFilePanel");
    this.hideFilePanel.setCheckable(true);
    this.checkUpdate = new QAction(black);
    this.checkUpdate.setObjectName("checkUpdate");
    this.centralwidget = new QWidget(black);
    this.centralwidget.setObjectName("centralwidget");
    this.verticalLayout = new QVBoxLayout(this.centralwidget);
    this.verticalLayout.setObjectName("verticalLayout");
    black.setCentralWidget(this.centralwidget);
    this.menubar = new QMenuBar(black) {
    	@Override
    	public boolean eventFilter(QObject o, QEvent e) {
    		// TODO Auto-generated method stub
//    		System.out.println("menubar "+e.type());
    		if(e.type() == QEvent.Type.ShortcutOverride)return true;
    		return super.eventFilter(o, e);
    		
    	}
    };
    menubar.setShortcutEnabled(Qt.Key.Key_Alt.value(), false);
    menubar.installEventFilter(menubar);
    this.menubar.setObjectName("menubar");
    this.menubar.setGeometry(new QRect(0, 0, 856, 23));
    this.fileMenu = new QMenu(this.menubar);
    this.fileMenu.setObjectName("menu");
    this.editMenu = new QMenu(this.menubar);
    this.editMenu.setObjectName("menu_2");
    this.projectMenu = new QMenu(this.menubar);
    this.projectMenu.setObjectName("menu_3");
//    this.menu_4 = new QMenu(this.menubar);
//    this.menu_4.setObjectName("menu_4");
//    this.menu_5 = new QMenu(this.menubar);
//    this.menu_5.setObjectName("menu_5");
    this.gitMenu = new QMenu(this.menubar);
    this.gitMenu.setObjectName("menuGit");
    this.toolsMenu = new QMenu(this.menubar);
    this.toolsMenu.setObjectName("menu_6");
    this.getNames = new QMenu(this.toolsMenu);
    this.getNames.setObjectName("getNames");
    this.viewMenu = new QMenu(this.menubar);
    this.viewMenu.setObjectName("menu_7");
    this.helpMenu = new QMenu(this.menubar);
    this.helpMenu.setObjectName("menu_8");
    black.setMenuBar(this.menubar);
    this.dockTree = new QDockWidget(black);
    this.dockTree.setObjectName("dockTree");
    this.dockTree.setFeatures(QDockWidget.DockWidgetFeature.DockWidgetMovable);
    this.dockTree.setAllowedAreas(Qt.DockWidgetArea.NoDockWidgetArea);
    this.dockWidgetContents = new QWidget();
    this.dockWidgetContents.setObjectName("dockWidgetContents");
    this.dockTree.setWidget(this.dockWidgetContents);
    black.addDockWidget(Qt.DockWidgetArea.resolve(1), this.dockTree);
    
    this.menubar.addAction(this.fileMenu.menuAction());
    this.menubar.addAction(this.editMenu.menuAction());
    this.menubar.addAction(this.projectMenu.menuAction());
//    this.menubar.addAction(this.menu_4.menuAction());
//    this.menubar.addAction(this.menu_5.menuAction());
    this.menubar.addAction(this.gitMenu.menuAction());
    this.menubar.addAction(this.toolsMenu.menuAction());
    this.menubar.addAction(this.viewMenu.menuAction());
    this.menubar.addAction(this.helpMenu.menuAction());
    this.fileMenu.addAction(this.newProject);
    this.fileMenu.addAction(this.openProject);
    this.editMenu.addAction(this.find);
    this.projectMenu.addAction(this.addFile);
    this.projectMenu.addAction(this.addDir);
    this.projectMenu.addAction(this.addKeywords);
    this.projectMenu.addSeparator();
    this.projectMenu.addAction(this.moveToRecycle);
    this.projectMenu.addAction(this.clearRecycle);
    this.projectMenu.addAction(this.resetProject);
    this.projectMenu.addSeparator();
    this.projectMenu.addAction(this.saveProjectAllChanged);
    this.projectMenu.addAction(this.openProjectDir);
    this.projectMenu.addAction(this.clearTempFiles);
    this.gitMenu.addAction(this.setGit);
    this.gitMenu.addAction(this.commit);
    this.gitMenu.addAction(this.push);
    this.gitMenu.addAction(this.commitAndPush);
    this.gitMenu.addSeparator();
//    this.gitMenu.addAction(this.branchTool);
    this.toolsMenu.addAction(this.charCount);
    this.toolsMenu.addAction(this.getNames.menuAction());
    this.projectMenu.addAction(this.clearLogs);
    this.getNames.addAction(this.oneChineseName);
    this.getNames.addAction(this.chineseNames);
    this.getNames.addAction(this.engManName);
    this.getNames.addAction(this.engWomanName);
    this.getNames.addAction(this.itManName);
    this.getNames.addAction(this.itWomanName);
    this.viewMenu.addAction(this.writingview);
    this.viewMenu.addAction(this.hideFilePanel);
    this.viewMenu.addSeparator();
    this.viewMenu.addAction(this.settings);
    this.helpMenu.addAction(this.checkUpdate);
    this.helpMenu.addAction(this.about);
    helpMenu.addAction(info);
    this.helpMenu.addSeparator();
    this.helpMenu.addAction(this.howPay);
    retranslateUi(black);
    
  }
  
  void retranslateUi(QMainWindow black)
  {
    black.setWindowTitle(QCoreApplication.translate("black", appInfo.appName, null));
    this.addFile.setText(QCoreApplication.translate("black", "添加文件", null));
    this.addDir.setText(QCoreApplication.translate("black", "添加文件夹", null));
    this.addKeywords.setText(QCoreApplication.translate("black", "添加关键词列表", null));
    this.newProject.setText(QCoreApplication.translate("black", "新建项目", null));
    this.openProject.setText(QCoreApplication.translate("black", "打开项目", null));
    this.find.setText(QCoreApplication.translate("black", "查找/替换", null));
    this.find.setShortcut(QCoreApplication.translate("black", "Ctrl+F", null));
    this.moveToRecycle.setText(QCoreApplication.translate("black", "将所选项目移到废纸篓", null));
    this.clearRecycle.setText(QCoreApplication.translate("black", "清空废纸篓", null));
    this.setGit.setText(QCoreApplication.translate("black", "配置Git仓库", null));
    this.commit.setText(QCoreApplication.translate("black", "提交更改到本地仓库", null));
    this.push.setText(QCoreApplication.translate("black", "将更改上推至远程仓库", null));
    this.commitAndPush.setText(QCoreApplication.translate("black", "提交更改并上推至远程仓库", null));
    this.branchTool.setText(QCoreApplication.translate("black", "分支操作", null));
    this.charCount.setText(QCoreApplication.translate("black", "字数统计", null));
    this.charCount.setShortcut(QCoreApplication.translate("black", "Ctrl+K", null));
    this.oneChineseName.setText(QCoreApplication.translate("black", "产生一个中国人名并插入正文", null));
    this.oneChineseName.setShortcut(QCoreApplication.translate("black", "Alt+`", null));
    this.chineseNames.setText(QCoreApplication.translate("black", "产生20个中国人名", null));
    this.chineseNames.setShortcut(QCoreApplication.translate("black", "F6", null));
    this.engManName.setText(QCoreApplication.translate("black", "产生一个英文男名并插入正文", null));
    this.engManName.setShortcut(QCoreApplication.translate("black", "F2", null));
    this.engWomanName.setText(QCoreApplication.translate("black", "产生一个英文女名并插入正文", null));
    this.engWomanName.setShortcut(QCoreApplication.translate("black", "F3", null));
    this.itManName.setText(QCoreApplication.translate("black", "产生一个意大利男名并插入正文", null));
    this.itManName.setShortcut(QCoreApplication.translate("black", "F4", null));
    this.itWomanName.setText(QCoreApplication.translate("black", "产生一个意大利女名并插入正文", null));
    this.itWomanName.setShortcut(QCoreApplication.translate("black", "F5", null));
    this.writingview.setText(QCoreApplication.translate("black", "写作视图", null));
    this.writingview.setShortcut(QCoreApplication.translate("black", "F11", null));
    this.settings.setText(QCoreApplication.translate("black", "首选项", null));
    this.settings.setShortcut(QCoreApplication.translate("black", "F1", null));
    this.resetProject.setText(QCoreApplication.translate("black", "重置项目", null));
    this.about.setText(QCoreApplication.translate("black", "关于", null));
    this.info.setText(QCoreApplication.translate("black", "免责声明", null));

    this.howPay.setText(QCoreApplication.translate("black", "捐助开发者", null));

    this.saveProjectAllChanged.setText(QCoreApplication.translate("black", "保存项目中的所有更改\tCtrl+S", null));
    this.openProjectDir.setText(QCoreApplication.translate("black", "打开项目所在目录", null));
    this.clearTempFiles.setText(QCoreApplication.translate("black", "清空项目缓存数据", null));
    this.clearLogs.setText(QCoreApplication.translate("black", "清空日志", null));
    this.hideFilePanel.setText(QCoreApplication.translate("black", "隐藏文件篓", null));
    this.hideFilePanel.setShortcut(QCoreApplication.translate("black", "Ctrl+Shift+B", null));
    this.checkUpdate.setText(QCoreApplication.translate("black", "检查新版本", null));
    this.fileMenu.setTitle(QCoreApplication.translate("black", "文件", null));
    this.editMenu.setTitle(QCoreApplication.translate("black", "编辑", null));
    this.projectMenu.setTitle(QCoreApplication.translate("black", "项目", null));
//    this.menu_4.setTitle(QCoreApplication.translate("black", "插入", null));
//    this.menu_5.setTitle(QCoreApplication.translate("black", "格式", null));
    this.gitMenu.setTitle(QCoreApplication.translate("black", "Git", null));
    this.toolsMenu.setTitle(QCoreApplication.translate("black", "工具", null));
    this.getNames.setTitle(QCoreApplication.translate("black", "人名产生", null));
    this.viewMenu.setTitle(QCoreApplication.translate("black", "视图", null));
    this.helpMenu.setTitle(QCoreApplication.translate("black", "帮助", null));
  }
}
